#!/bin/bash
read file_name
echo "enter file name"
if [ -f $file_name ]
then
  if [ -w $file_name ]
  then
     echo  "type some data to quit ctrl+d"
     cat >> $file_name
  else
     echo "the file does not have write permission"
     fi
else
echo "$file_name not exists"
fi

